In [301]:
import numpy as np
sales_data = np.array([
    [[30, 40, 35], [45, 55, 50], [25, 30, 28], [35, 38, 40]],
    [[20, 25, 30], [18, 20, 22], [40, 38, 36], [15, 10, 12]],
    [[50, 55, 60], [60, 65, 70], [45, 48, 50], [55, 50, 58]]
])

# 1 display sales_data
sales_data


array([[[30, 40, 35],
        [45, 55, 50],
        [25, 30, 28],
        [35, 38, 40]],

       [[20, 25, 30],
        [18, 20, 22],
        [40, 38, 36],
        [15, 10, 12]],

       [[50, 55, 60],
        [60, 65, 70],
        [45, 48, 50],
        [55, 50, 58]]])

In [302]:
# 2 displays the sum of each product's sales for all months

sumProduct = np.sum(np.sum(sales_data , axis=1) , axis=0)
sumProduct
#np.sum(sales_data , axis=1)

array([438, 474, 491])

In [303]:
# 3 display the average per month
average_for_month = np.round(np.mean(np.mean(sales_data  , axis=1) , axis= 0) , 2)
average_for_month

array([36.5 , 39.5 , 40.92])

In [304]:
# 4 display the month with the highest sales per product
the_best_months = np.argmax(sales_data, axis=1)
the_best_months
np.max(sales_data[:,: , 0])
for i  in range(sales_data.shape[1] - 1) :
    print(f'journal of all  product {i + 1} sales : \n' , sales_data[:,:,i] )
    print(f'the best month of the product {i + 1} :  month { np.argmax(sales_data[:,: , i]) + 1} ')
    print(f'with {np.max(sales_data[:,: , i])}  sold ')
    
    



journal of all  product 1 sales : 
 [[30 45 25 35]
 [20 18 40 15]
 [50 60 45 55]]
the best month of the product 1 :  month 10 
with 60  sold 
journal of all  product 2 sales : 
 [[40 55 30 38]
 [25 20 38 10]
 [55 65 48 50]]
the best month of the product 2 :  month 10 
with 65  sold 
journal of all  product 3 sales : 
 [[35 50 28 40]
 [30 22 36 12]
 [60 70 50 58]]
the best month of the product 3 :  month 10 
with 70  sold 


In [305]:
# 5 and 6 the new dimension for the quarter and assign the sum of product 'sales in each quarter
 
newData = np.array([])
newData.resize(3,5,3)
newData[: , : 4 , : ] = sales_data  
newData[: , 4, : ] =  np.sum(newData[: , : 4 , : ] , axis=1 )
%timeit newData

25.6 ns ± 5.97 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [306]:
#  7 display the sales of two products

newData[: , : ,  : 2 ]



array([[[ 30.,  40.],
        [ 45.,  55.],
        [ 25.,  30.],
        [ 35.,  38.],
        [135., 163.]],

       [[ 20.,  25.],
        [ 18.,  20.],
        [ 40.,  38.],
        [ 15.,  10.],
        [ 93.,  93.]],

       [[ 50.,  55.],
        [ 60.,  65.],
        [ 45.,  48.],
        [ 55.,  50.],
        [210., 218.]]])

In [307]:
# 8 replace the third product sale for the second month by an random value between 30 and 60

newData[0, 1 ,2] = np.random.randint(30,60)
newData[: , 4, : ] =  np.sum(newData[: , : 4 , : ] , axis=1 )
newData

array([[[ 30.,  40.,  35.],
        [ 45.,  55.,  43.],
        [ 25.,  30.,  28.],
        [ 35.,  38.,  40.],
        [135., 163., 146.]],

       [[ 20.,  25.,  30.],
        [ 18.,  20.,  22.],
        [ 40.,  38.,  36.],
        [ 15.,  10.,  12.],
        [ 93.,  93., 100.]],

       [[ 50.,  55.,  60.],
        [ 60.,  65.,  70.],
        [ 45.,  48.,  50.],
        [ 55.,  50.,  58.],
        [210., 218., 238.]]])

In [308]:
# 9 display the product with the best quarter
for i in range(newData.shape[2]):
    if np.any(newData[:,:,i] == np.max(newData))  :
        print(f'the product {i} has the best quarter with {np.max(newData)}')
    



the product 2 has the best quarter with 238.0


In [309]:
# 10 sort the data_sales by the  months for each product
newData[:, :4, :].sort()

newData

array([[[ 30.,  35.,  40.],
        [ 43.,  45.,  55.],
        [ 25.,  28.,  30.],
        [ 35.,  38.,  40.],
        [135., 163., 146.]],

       [[ 20.,  25.,  30.],
        [ 18.,  20.,  22.],
        [ 36.,  38.,  40.],
        [ 10.,  12.,  15.],
        [ 93.,  93., 100.]],

       [[ 50.,  55.,  60.],
        [ 60.,  65.,  70.],
        [ 45.,  48.,  50.],
        [ 50.,  55.,  58.],
        [210., 218., 238.]]])

In [310]:
unityPrice = np.array([0.05 , 0.08 , 0.06])
turnover = np.array([])
turnover = newData * unityPrice
turnover
 


array([[[ 1.5 ,  2.8 ,  2.4 ],
        [ 2.15,  3.6 ,  3.3 ],
        [ 1.25,  2.24,  1.8 ],
        [ 1.75,  3.04,  2.4 ],
        [ 6.75, 13.04,  8.76]],

       [[ 1.  ,  2.  ,  1.8 ],
        [ 0.9 ,  1.6 ,  1.32],
        [ 1.8 ,  3.04,  2.4 ],
        [ 0.5 ,  0.96,  0.9 ],
        [ 4.65,  7.44,  6.  ]],

       [[ 2.5 ,  4.4 ,  3.6 ],
        [ 3.  ,  5.2 ,  4.2 ],
        [ 2.25,  3.84,  3.  ],
        [ 2.5 ,  4.4 ,  3.48],
        [10.5 , 17.44, 14.28]]])