# Exercice : Manipulation avancée de données avec NumPy

# Vous travaillez avec les résultats de cinq étudiants pour six devoirs (chaque note est sur 20).
# Générez un tableau de données pour représenter cela.

# 1. Affichez le tableau des résultats.

# 2. Calculez et affichez la moyenne de chaque étudiant.

# 3. Calculez et affichez la moyenne de chaque devoir.

# 4. Ajoutez une colonne représentant la note d'un projet (sur 50).

# 5. Calculez et affichez la moyenne de chaque étudiant, y compris la note du projet.

# 6. Trouvez et affichez les devoirs où la note moyenne de la classe est inférieure à 15.

# 7. Remplacez les notes des deux derniers étudiants pour le deuxième devoir par des notes aléatoires entre 10 et 15.

# 8. Tirez aléatoirement les notes pour un nouvel étudiant et ajoutez-les comme une nouvelle ligne dans le tableau.

# 9. Calculez et affichez la transposée du tableau (échangez les lignes et les colonnes).

# 10. Calculez et affichez la somme cumulative des notes de chaque étudiant pour chaque devoir.

# 11. Trouvez et affichez l'indice de l'étudiant avec la meilleure performance (la somme cumulative la plus élevée).

# 12. Bonus : Calculez la médiane de chaque devoir.

# Votre code ici...

In [198]:

import numpy as np

data_set = np.random.randint(0,20,size=(5,6))
data_set

 



array([[ 6,  4, 16, 15,  4, 10],
       [ 0,  8,  7, 16,  1, 14],
       [ 2, 19,  4, 17,  8, 16],
       [18, 19,  1,  8,  6,  0],
       [17, 16, 15, 10,  0,  2]])

In [199]:
# 2  display the average of each student 
average_student = np.round(np.mean(data_set , axis= 1),2)
average_student

array([ 9.17,  7.67, 11.  ,  8.67, 10.  ])

In [200]:
# 3 display the average of each course
average_course = np.round(np.mean(data_set , axis= 0),2)
average_course

array([ 8.6, 13.2,  8.6, 13.2,  3.8,  8.4])

In [201]:
# 4  add a score project
project_score = np.random.randint(0,50,size=(5))

data_set = np.hstack((data_set , project_score.reshape(-1,1)))
data_set



array([[ 6,  4, 16, 15,  4, 10, 33],
       [ 0,  8,  7, 16,  1, 14,  0],
       [ 2, 19,  4, 17,  8, 16, 23],
       [18, 19,  1,  8,  6,  0, 48],
       [17, 16, 15, 10,  0,  2,  8]])

In [202]:
# 5 calculate the big average
big_average = np.round(np.mean(data_set,axis= 1),2)
big_average

array([12.57,  6.57, 12.71, 14.29,  9.71])

In [203]:
# 6 display the examen  average less than 15
less_than_15 =  np.where(np.mean(data_set , axis= 0) < 15 )
less_than_15


(array([0, 1, 2, 3, 4, 5], dtype=int64),)

In [204]:
# 7 replace the second student score at the second examen by  random number between 10 and  15

data_set[1,1]  = np.random.randint(10,15)
data_set

array([[ 6,  4, 16, 15,  4, 10, 33],
       [ 0, 13,  7, 16,  1, 14,  0],
       [ 2, 19,  4, 17,  8, 16, 23],
       [18, 19,  1,  8,  6,  0, 48],
       [17, 16, 15, 10,  0,  2,  8]])

In [205]:
# 8 add new student

new_student = np.random.randint(0,20,size=(7))
new_student[-1] = np.random.randint(0,50)
data_set = np.vstack((data_set , new_student))
data_set

array([[ 6,  4, 16, 15,  4, 10, 33],
       [ 0, 13,  7, 16,  1, 14,  0],
       [ 2, 19,  4, 17,  8, 16, 23],
       [18, 19,  1,  8,  6,  0, 48],
       [17, 16, 15, 10,  0,  2,  8],
       [ 4, 15, 19,  4, 17, 16, 25]])

In [206]:
# transpose a dataset
data_set.T

array([[ 6,  0,  2, 18, 17,  4],
       [ 4, 13, 19, 19, 16, 15],
       [16,  7,  4,  1, 15, 19],
       [15, 16, 17,  8, 10,  4],
       [ 4,  1,  8,  6,  0, 17],
       [10, 14, 16,  0,  2, 16],
       [33,  0, 23, 48,  8, 25]])

In [207]:
#display the cumsum of each student

cumsum = np.cumsum(data_set , axis= 1)
cumsum

array([[  6,  10,  26,  41,  45,  55,  88],
       [  0,  13,  20,  36,  37,  51,  51],
       [  2,  21,  25,  42,  50,  66,  89],
       [ 18,  37,  38,  46,  52,  52, 100],
       [ 17,  33,  48,  58,  58,  60,  68],
       [  4,  19,  38,  42,  59,  75, 100]])

In [208]:
the_best_student = np.where(cumsum == np.amax(cumsum))
print(f'student {the_best_student[0][0] + 1} is the best with {np.amax(cumsum)}')

student 4 is the best with 100


In [209]:
median_examen = np.median(data_set , axis= 0)
median_examen

array([ 5. , 15.5, 11. , 12.5,  5. , 12. , 24. ])