In [399]:
#Get a specific row tab[r , c]
#indexation is :
#tab[r(index :position :step) , c(index :position :step)]

In [400]:
import numpy as np
data  = np.array([
    [85, 90, 88],
    [89, 92, 91],
    [78, 85, 80],
    [92, 88, 89]
])

In [401]:
#afficher data

print(data)
 

[[85 90 88]
 [89 92 91]
 [78 85 80]
 [92 88 89]]


In [429]:
#display the second team score in the first test
data[1 , 0]

89

In [403]:
#display the all team scores in  the second test

data[: , 1]

array([90, 92, 85, 88])

In [404]:
#display the third test score of two first team
data[0:2,2]

array([88, 91])

In [424]:
#
theMean = np.array([round(np.mean(x) , 3) for x in data])
#theMean = round(np.mean(data , axis= 1))
print(theMean)
 

[87.667 91.667 81.    89.667]


In [425]:
#display the highest scrore in the first test
highFirstTest = np.argmax(data[:,0])
#highFirstTest = data[: ,0].max()
print(highFirstTest)

3


In [407]:
#change the second team scrore in second test by 95
data[1 ,1] = 95

In [430]:
# add a new team in data
newData = np.append(data, [90,86,88])
newData = np.reshape(newData , (5 , 3))
newData


array([[85, 90, 88],
       [89, 95, 91],
       [78, 85, 80],
       [92, 88, 89],
       [90, 86, 88]])

In [428]:
#say which team get more than 89 in first test
#mask = data[:, 0] >= 90
#print(data[mask])
rang = np.array(["first" , "second" , "third" , "fourth" , "fifth"])
for k , x in enumerate(newData[: , 0]):
    if x >= 90 :
        print(f'the {rang[k] } team has {x}')

the fourth team has 92
the fifth team has 90


In [410]:
# display the first and last score of all teams
top_score = newData[:,0 : 3 : 2]
top_score


array([[85, 88],
       [89, 91],
       [78, 80],
       [92, 89],
       [90, 88]])

In [416]:
#mutiply  the tab top score by 2

double = top_score * 2
double


array([[170, 176],
       [178, 182],
       [156, 160],
       [184, 178],
       [180, 176]])

In [427]:
indices = np.where((data[:, 0] == 85) & (data[:, -1] == 85))
