In [14]:
import numpy as np

# Tableau de données (résultats de l'examen)
data = np.array([
    [78, 92, 85, 88],
    [88, 85, 90, 82],
    [68, 75, 80, 74],
    [95, 98, 92, 93],
    [82, 88, 78, 85]
])

print(data)

[[78 92 85 88]
 [88 85 90 82]
 [68 75 80 74]
 [95 98 92 93]
 [82 88 78 85]]


In [15]:
theMean = [np.round(np.mean(x) , 2) for x in data]
theMean

[85.75, 86.25, 74.25, 94.5, 83.25]

In [16]:
data = np.column_stack((data , np.round(theMean)))
data

array([[78., 92., 85., 88., 86.],
       [88., 85., 90., 82., 86.],
       [68., 75., 80., 74., 74.],
       [95., 98., 92., 93., 94.],
       [82., 88., 78., 85., 83.]])

In [17]:
highest = data[np.where(data > 90 )]
highest

array([92., 95., 98., 92., 93., 94.])

In [18]:
data[: , 3] += 5
data 

array([[78., 92., 85., 93., 86.],
       [88., 85., 90., 87., 86.],
       [68., 75., 80., 79., 74.],
       [95., 98., 92., 98., 94.],
       [82., 88., 78., 90., 83.]])

In [27]:
pass_fail = np.where(data[:,:3] >= 80 ,"win" ,"fail" )
pass_fail

array([['fail', 'win', 'win'],
       ['win', 'win', 'win'],
       ['fail', 'fail', 'win'],
       ['win', 'win', 'win'],
       ['win', 'win', 'fail']], dtype='<U4')

In [29]:
num_fail = np.sum(pass_fail == 'fail')
num_win = np.sum(pass_fail == 'win')
print(num_fail)
num_win

4


11

In [31]:
data = data[data[:,1].argsort()]
data

array([[68., 75., 80., 79., 74.],
       [88., 85., 90., 87., 86.],
       [82., 88., 78., 90., 83.],
       [78., 92., 85., 93., 86.],
       [95., 98., 92., 98., 94.]])

In [32]:
data[:2 , 1]

array([75., 85.])

In [34]:
best_subject = np.max(data , axis= 0)
best_subject

array([95., 98., 92., 98., 94.])