import numpy as np

# Exercice : Opérations avec NumPy

# Générez un tableau 2D représentant les notes des étudiants pour trois matières (10 étudiants, 3 matières).
# Les notes doivent être des nombres entiers aléatoires entre 0 et 100 inclus.

# 1. Affichez le tableau des notes.

# 2. Calculez et affichez la moyenne des notes pour chaque étudiant.

# 3. Trouvez et affichez le numéro de l'étudiant avec la meilleure moyenne.

# 4. Ajoutez une nouvelle matière (quatrième colonne) représentant les notes d'un nouvel examen.
#    Les notes doivent être des nombres aléatoires entre 50 et 90 inclus.

# 5. Calculez et affichez la moyenne des notes pour chaque matière.

# 6. Sélectionnez et affichez les notes des étudiants qui ont réussi tous les examens (moyenne >= 60).

# 7. Remplacez les notes du deuxième étudiant dans la première matière par la note maximale possible (100).

# 8. Triez le tableau des notes par ordre décroissant des moyennes des étudiants.

# 9. Affichez le tableau après chaque opération pour vérifier les résultats.

# 10. Bonus : Calculez la médiane des notes pour chaque matière.

# Votre code ici...


np.random.seed(42)  # Pour assurer la reproductibilité des résultats
grades = np.random.randint(0, 101, size=(10, 3))

In [507]:
import numpy as np 

# 1 set data with random value
note = np.ones((10,3))
for i in range(note.shape[0]) :
    for j in range(note.shape[1]):
        note[i , j] = np.random.randint(30 , 100)
    


note 

array([[93., 74., 98.],
       [37., 63., 72.],
       [91., 85., 48.],
       [85., 50., 93.],
       [61., 33., 98.],
       [52., 82., 91.],
       [89., 41., 91.],
       [93., 62., 49.],
       [74., 41., 61.],
       [63., 70., 91.]])

In [508]:
# 2 average for each  student

average = np.round(np.mean(note[:,:] , axis= 1) , 2)
average

array([88.33, 57.33, 74.67, 76.  , 64.  , 75.  , 73.67, 68.  , 58.67,
       74.67])

In [509]:
# 3 display the student with the best average 

print(f'The student {np.argmax(average)} is the best with {np.max(average)}')

The student 0 is the best with 88.33


new_exam_scores = np.random.randint(50, 91, size=(10, 1))
grades = np.hstack((grades, new_exam_scores))

In [510]:
#  4 add a new column
a = np.ones((10))
for i in  range(10):
    a[i] = np.random.choice(np.arange(50,90))
a
note = np.concatenate((a.reshape(-1,1) , note) , axis= 1)


In [511]:
# 5 calculate the average by course
average_by_course = np.mean(note , axis=0)
average_by_course

array([70.3, 73.8, 60.1, 79.2])

In [512]:
# 6 display the student with average >= 60 
np.where(average >= 60 , average    , 0).reshape(-1,1)

array([[88.33],
       [ 0.  ],
       [74.67],
       [76.  ],
       [64.  ],
       [75.  ],
       [73.67],
       [68.  ],
       [ 0.  ],
       [74.67]])

In [513]:
# 7 replace the first score of second student by 100
note[1,0] = 100
note

array([[ 65.,  93.,  74.,  98.],
       [100.,  37.,  63.,  72.],
       [ 83.,  91.,  85.,  48.],
       [ 68.,  85.,  50.,  93.],
       [ 57.,  61.,  33.,  98.],
       [ 69.,  52.,  82.,  91.],
       [ 89.,  89.,  41.,  91.],
       [ 58.,  93.,  62.,  49.],
       [ 56.,  74.,  41.,  61.],
       [ 84.,  63.,  70.,  91.]])

In [515]:
#8  
note.sort()
note


array([[ 65.,  74.,  93.,  98.],
       [ 37.,  63.,  72., 100.],
       [ 48.,  83.,  85.,  91.],
       [ 50.,  68.,  85.,  93.],
       [ 33.,  57.,  61.,  98.],
       [ 52.,  69.,  82.,  91.],
       [ 41.,  89.,  89.,  91.],
       [ 49.,  58.,  62.,  93.],
       [ 41.,  56.,  61.,  74.],
       [ 63.,  70.,  84.,  91.]])

In [517]:
#9
mediane = np.median(note)
mediane

71.0