import numpy as np

# Exercice : Manipulation de données avec NumPy

# Imaginez que vous ayez les résultats de trois étudiants pour quatre devoirs (chaque note est sur 20).
# Générez un tableau de données pour représenter cela.

# 1. Affichez le tableau des résultats.

# 2. Calculez et affichez la moyenne de chaque étudiant.

# 3. Calculez et affichez la moyenne de chaque devoir.

# 4. Ajoutez une colonne représentant la note d'un examen final (sur 100).

# 5. Calculez et affichez la moyenne de chaque étudiant, y compris la note de l'examen final.

# 6. Trouvez et affichez les étudiants qui ont obtenu une moyenne supérieure à 15.

# 7. Remplacez la note du deuxième étudiant pour le deuxième devoir par une note parfaite (20).

# 8. Tirez aléatoirement les notes pour un nouvel étudiant et ajoutez-les comme une nouvelle ligne dans le tableau.

# 9. Calculez et affichez la transposée du tableau (échangez les lignes et les colonnes).

# 10. Bonus : Calculez la médiane de chaque devoir.

# Votre code ici...


In [146]:
import numpy as np
data_set = np.random.randint(0,20 , size=(3,4))
data_set

array([[ 9,  3, 15, 13],
       [13, 14, 11,  6],
       [17, 15, 17, 18]])

In [147]:
# 2 display th average of each student
average_student = np.round(np.mean(data_set , axis=1) , 2)
average_student

array([10.  , 11.  , 16.75])

In [148]:
# 3 display th average of each course
average_course =  np.round(np.mean(data_set , axis=0) , 2)
average_course



array([13.  , 10.67, 14.33, 12.33])

In [149]:
# 4 add a fianl examen
finalExamen = np.random.randint(30,100, size=(3))
finalExamen
data_set = np.concatenate((data_set , finalExamen.reshape(-1,1)) , axis= 1)
data_set

array([[ 9,  3, 15, 13, 98],
       [13, 14, 11,  6, 62],
       [17, 15, 17, 18, 43]])

In [150]:
# 5 make a big average
big_average = np.round(np.mean(data_set , axis= 1) , 2)
big_average

array([27.6, 21.2, 22. ])

high_scorers = np.where(average_scores_students_with_final > 15)[0]
print("6. Étudiants ayant une moyenne supérieure à 15 :")
print(high_scorers)
print()

In [156]:
# 6 find out the student with a average bigger than 15

bigger_than_15 = np.where(big_average > 15  , big_average , 0 )
bigger_than_15



array([27.6, 21.2, 22. ])

In [152]:
# 7  replace the second student score of student at the position 2 by 20
data_set[1,1] = 20
data_set


array([[ 9,  3, 15, 13, 98],
       [13, 20, 11,  6, 62],
       [17, 15, 17, 18, 43]])

In [153]:
# 8 add  a  new student
new_student = np.random.randint(0,20,size=(5))
new_student[4] = np.random.randint(0,100)
data_set = np.vstack((data_set , new_student))
data_set

array([[ 9,  3, 15, 13, 98],
       [13, 20, 11,  6, 62],
       [17, 15, 17, 18, 43],
       [ 4, 18,  6, 19, 92]])

In [154]:
# 9 transpose the data_set 

np.transpose(data_set)

array([[ 9, 13, 17,  4],
       [ 3, 20, 15, 18],
       [15, 11, 17,  6],
       [13,  6, 18, 19],
       [98, 62, 43, 92]])

In [155]:
np.median(data_set , axis= 0)

array([11. , 16.5, 13. , 15.5, 77. ])